import { MetadataRoute } from "next";
import { siteConfig } from "@/lib/metadata";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/food",
          "/map",
          "/food/",
          "/forum",
          "/forum/",
          "/challenge",
          "/help",
          "/terms",
          "/privacy",
        ],
        disallow: [
          "/api/",
          "/admin/",
          "/profile/edit",
          "/settings/",
          "/auth/",
          "/_next/",
          "/food/new",
          "/food/*/edit",
          "/forum/new",
          "/chat",
          "/user-listings",
          "/maintenance",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: ["/", "/food", "/map", "/food/", "/profile/", "/forum", "/forum/", "/challenge"],
        disallow: [
          "/api/",
          "/admin/",
          "/profile/edit",
          "/settings/",
          "/auth/",
          "/food/new",
          "/food/*/edit",
          "/forum/new",
          "/chat",
          "/user-listings",
        ],
      },
      // Social media crawlers - allow all public content
      {
        userAgent: "Twitterbot",
        allow: ["/"],
      },
      {
        userAgent: "facebookexternalhit",
        allow: ["/"],
      },
      {
        userAgent: "LinkedInBot",
        allow: ["/"],
      },
      {
        userAgent: "WhatsApp",
        allow: ["/"],
      },
      {
        userAgent: "TelegramBot",
        allow: ["/"],
      },
      // AI crawlers - allow public content for GEO (Generative Engine Optimization)
      // This enables visibility in ChatGPT Search, Perplexity, Google AI Mode
      {
        userAgent: "GPTBot",
        allow: ["/", "/food", "/forum", "/help", "/map", "/challenge", "/terms", "/privacy"],
        disallow: [
          "/api/",
          "/admin/",
          "/settings/",
          "/auth/",
          "/chat",
          "/profile/edit",
          "/food/new",
          "/food/*/edit",
          "/forum/new",
          "/user-listings",
        ],
      },
      {
        userAgent: "ChatGPT-User",
        allow: ["/", "/food", "/forum", "/help", "/map", "/challenge", "/terms", "/privacy"],
        disallow: [
          "/api/",
          "/admin/",
          "/settings/",
          "/auth/",
          "/chat",
          "/profile/edit",
          "/food/new",
          "/food/*/edit",
          "/forum/new",
          "/user-listings",
        ],
      },
      {
        userAgent: "CCBot",
        allow: ["/", "/food", "/forum", "/help", "/map", "/challenge", "/terms", "/privacy"],
        disallow: [
          "/api/",
          "/admin/",
          "/settings/",
          "/auth/",
          "/chat",
          "/profile/edit",
          "/food/new",
          "/food/*/edit",
          "/forum/new",
          "/user-listings",
        ],
      },
      {
        userAgent: "anthropic-ai",
        allow: ["/", "/food", "/forum", "/help", "/map", "/challenge", "/terms", "/privacy"],
        disallow: [
          "/api/",
          "/admin/",
          "/settings/",
          "/auth/",
          "/chat",
          "/profile/edit",
          "/food/new",
          "/food/*/edit",
          "/forum/new",
          "/user-listings",
        ],
      },
      {
        userAgent: "PerplexityBot",
        allow: ["/", "/food", "/forum", "/help", "/map", "/challenge", "/terms", "/privacy"],
        disallow: [
          "/api/",
          "/admin/",
          "/settings/",
          "/auth/",
          "/chat",
          "/profile/edit",
          "/food/new",
          "/food/*/edit",
          "/forum/new",
          "/user-listings",
        ],
      },
      {
        userAgent: "Google-Extended",
        allow: ["/", "/food", "/forum", "/help", "/map", "/challenge", "/terms", "/privacy"],
        disallow: [
          "/api/",
          "/admin/",
          "/settings/",
          "/auth/",
          "/chat",
          "/profile/edit",
          "/food/new",
          "/food/*/edit",
          "/forum/new",
          "/user-listings",
        ],
      },
    ],
    sitemap: [`${siteConfig.url}/sitemap.xml`, `${siteConfig.url}/forum/feed.xml`],
    host: siteConfig.url,
  };
}
