export const PATH = {
  main: "/",
  mainFood: "/food",
  // Category routes (plural for better UX, mapped to singular DB post_type in components)
  food: "/food",
  thing: "/thing",
  borrow: "/borrow",
  wanted: "/wanted",
  foodbank: "/foodbank",
  fridge: "/fridge",
  organisation: "/organisation",
  volunteer: "/volunteer",
  challenge: "/challenge",
  forum: "/forum",
  vegan: "/vegan",
  zerowaste: "/zerowaste",
  // Other routes
  productPage: "/:type/:id",
  aboutUsPage: "/about-us",
  contactUsPage: "/contact-us",
  volunteerPage: "/volunteer",
  myListingsPage: `/user-listings`,
  searchResultsPage: "/:type",
  settingsPage: "/settings",
  personalInfoPage: "/settings/personal-info",
  loginSecurityPage: "/settings/login-and-security",
  donationPage: "/donation",
  feedbackPage: "/feedback",
  leaderboardPage: "/leaderboard",
  mapPage: "/map/:type",
  // Auth routes
  authLogin: "/auth/login",
  authCallback: "/auth/callback",
  // Admin CRM routes
  adminDashboard: "/admin",
  adminListings: "/admin/listings",
  adminUsers: "/admin/users",
  adminReports: "/admin/reports",
  adminEmail: "/admin/email",
  adminEmailTest: "/admin/email/test",
  adminEmailMonitor: "/admin/email/monitor",
  adminAIInsights: "/admin/ai-insights",
} as const;
